/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_akhir_pbo.views;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import project_akhir_pbo.controllers.AdminMainController;

/**
 *
 * @author Salma Hanifa
 */
public class AdminMainView extends javax.swing.JFrame {

    /**
     * Creates new form AdminMainView
     */
    AdminMainController c;
    public AdminMainView(AdminMainController c) {
        initComponents();
        this.c = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTableRequest = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dataTableAcc = new javax.swing.JTable();
        accButton = new javax.swing.JButton();
        detailButton = new javax.swing.JButton();
        tolakButton = new javax.swing.JButton();
        dissButton = new javax.swing.JButton();
        detailDoneButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel1.setText("Data Kelompok Belum Dikonfirmasi");

        dataTableRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dataTableRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataTableRequestMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dataTableRequest);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel2.setText("Data Kelompok Sudah Dikonfirmasi");

        dataTableAcc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dataTableAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataTableAccMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(dataTableAcc);

        accButton.setBackground(new java.awt.Color(180, 226, 226));
        accButton.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        accButton.setText("Terima");
        accButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accButtonMouseClicked(evt);
            }
        });

        detailButton.setBackground(new java.awt.Color(204, 204, 204));
        detailButton.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        detailButton.setText("Detail");
        detailButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detailButtonMouseClicked(evt);
            }
        });

        tolakButton.setBackground(new java.awt.Color(255, 204, 204));
        tolakButton.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        tolakButton.setText("Tolak");
        tolakButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tolakButtonMouseClicked(evt);
            }
        });

        dissButton.setBackground(new java.awt.Color(255, 204, 204));
        dissButton.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        dissButton.setText("Diskualifikasi");
        dissButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dissButtonMouseClicked(evt);
            }
        });

        detailDoneButton.setBackground(new java.awt.Color(204, 204, 204));
        detailDoneButton.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        detailDoneButton.setText("Detail");
        detailDoneButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detailDoneButtonMouseClicked(evt);
            }
        });

        logoutButton.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 0, 51));
        logoutButton.setText("Log out");
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(detailButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tolakButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(accButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(dissButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(detailDoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detailDoneButton)
                    .addComponent(dissButton)
                    .addComponent(accButton)
                    .addComponent(tolakButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailButton)
                .addGap(52, 52, 52)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataTableRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataTableRequestMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dataTableRequestMouseClicked

    private void dataTableAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataTableAccMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dataTableAccMouseClicked

    private void accButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accButtonMouseClicked
        // TODO add your handling code here:
        int row = dataTableRequest.getSelectedRow();
        if (row == -1) {
            //Tampilan error tidak adad data yang dipilih
            JOptionPane.showMessageDialog(this, "Tidak ada data yang dipilih", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }else{
            String id = dataTableRequest.getModel().getValueAt(row, 0).toString();
            c.accKelompok(id);
        }
    }//GEN-LAST:event_accButtonMouseClicked

    private void detailButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailButtonMouseClicked
        // TODO add your handling code here:
        int row = dataTableRequest.getSelectedRow();
        if (row == -1) {
            //Tampilan error tidak adad data yang dipilih
            JOptionPane.showMessageDialog(this, "Tidak ada data yang dipilih", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }else{
            String id = dataTableRequest.getModel().getValueAt(row, 0).toString();
            c.getDetail(id);
        }
    }//GEN-LAST:event_detailButtonMouseClicked

    private void tolakButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tolakButtonMouseClicked
        // TODO add your handling code here:
        int row = dataTableRequest.getSelectedRow();
        if (row == -1) {
            //Tampilan error tidak adad data yang dipilih
            JOptionPane.showMessageDialog(this, "Tidak ada data yang dipilih", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }else{
            String id = dataTableRequest.getModel().getValueAt(row, 0).toString();
            c.tolakKelompok(id);
        }
    }//GEN-LAST:event_tolakButtonMouseClicked

    private void dissButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dissButtonMouseClicked
        // TODO add your handling code here:
        int row = dataTableAcc.getSelectedRow();
        if (row == -1) {
            //Tampilan error tidak adad data yang dipilih
            JOptionPane.showMessageDialog(this, "Tidak ada data yang dipilih", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }else{
            String id = dataTableAcc.getModel().getValueAt(row, 0).toString();
            c.dissKelompok(id);
        }
    }//GEN-LAST:event_dissButtonMouseClicked

    private void detailDoneButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailDoneButtonMouseClicked
        // TODO add your handling code here:
        int row = dataTableAcc.getSelectedRow();
        if (row == -1) {
            //Tampilan error tidak adad data yang dipilih
            JOptionPane.showMessageDialog(this, "Tidak ada data yang dipilih", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }else{
            String id = dataTableAcc.getModel().getValueAt(row, 0).toString();
            c.getDetail(id);
        }
    }//GEN-LAST:event_detailDoneButtonMouseClicked

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        // TODO add your handling code here:
        c.logOut();
    }//GEN-LAST:event_logoutButtonMouseClicked

    public JTable getDataTableAcc() {
        return dataTableAcc;
    }

    public JTable getDataTableRequest() {
        return dataTableRequest;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accButton;
    private javax.swing.JTable dataTableAcc;
    private javax.swing.JTable dataTableRequest;
    private javax.swing.JButton detailButton;
    private javax.swing.JButton detailDoneButton;
    private javax.swing.JButton dissButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton tolakButton;
    // End of variables declaration//GEN-END:variables
}
