/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_akhir_pbo.views;

import javax.swing.JOptionPane;
import project_akhir_pbo.controllers.KelompokLoginController;

/**
 *
 * @author Salma Hanifa
 */
public class KelompokLoginView extends javax.swing.JFrame {

    /**
     * Creates new form KelompokLoginView
     */
    KelompokLoginController c;
    public KelompokLoginView(KelompokLoginController c) {
        initComponents();
        this.c = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        namaField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        regisButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passField = new javax.swing.JPasswordField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setText("Login Kelompok");

        namaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaFieldActionPerformed(evt);
            }
        });

        loginButton.setBackground(new java.awt.Color(180, 226, 226));
        loginButton.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        loginButton.setText("Login");
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });

        regisButton.setBackground(new java.awt.Color(216, 234, 251));
        regisButton.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        regisButton.setText("Register");
        regisButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regisButtonMouseClicked(evt);
            }
        });
        regisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regisButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel2.setText("Nama Kelompok");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel3.setText("Password Kelompok");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(regisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(namaField)
                        .addComponent(jLabel2)
                        .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(133, 133, 133))
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaFieldActionPerformed

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        // TODO add your handling code here:
        if(namaField.getText().isEmpty() && passField.getText().isEmpty()){
            //Kasih error Username dan password tidak boleh kosong
            JOptionPane.showMessageDialog(this, "Nama kelompok dan password tidak boleh kosong", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }else if(namaField.getText().isEmpty()){
            //Kasih error Username kosong
            JOptionPane.showMessageDialog(this, "Nama kelompok tidak boleh kosong", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }else if(passField.getText().isEmpty()){
            //Kasih error Password tidak boleh kosong
            JOptionPane.showMessageDialog(this, "Password tidak boleh kosong", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }else{
            c.loginProcess(namaField.getText(), passField.getText());  
        }
    }//GEN-LAST:event_loginButtonMouseClicked

    private void regisButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regisButtonMouseClicked
        // TODO add your handling code here:
        if(namaField.getText().isEmpty() && passField.getText().isEmpty()){
            //Kasih error Username dan password tidak boleh kosong
            JOptionPane.showMessageDialog(this, "Nama kelompok dan password tidak boleh kosong", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }else if(namaField.getText().isEmpty()){
            //Kasih error Username kosong
            JOptionPane.showMessageDialog(this, "Nama kelompok tidak boleh kosong", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }else if(passField.getText().isEmpty()){
            //Kasih error Password tidak boleh kosong
            JOptionPane.showMessageDialog(this, "Password tidak boleh kosong", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }else{
            c.registerProcess(namaField.getText(), passField.getText()); 
        }
    }//GEN-LAST:event_regisButtonMouseClicked

    private void regisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regisButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regisButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField namaField;
    private javax.swing.JPasswordField passField;
    private javax.swing.JButton regisButton;
    // End of variables declaration//GEN-END:variables
}
